### ISSUE TITLE
Crash in Android 11 - getDefaultSmsPackage() returns null

### ISSUE THREAD

**Issue by JanuszHain** [denyszelenchuk/sms-to-slack#1]
It is due to lack of permission for quering the package of sms app.

[Manifest code addition fixes the issue](https://stackoverflow.com/questions/66867337/getdefaultsmspackage-return-null-in-android-11):

```
    <queries>
        <intent>
            <action android:name="android.intent.action.SENDTO" />
            <data
                android:host="*"
                android:scheme="smsto" />
        </intent>
    </queries>
```

**Comment by denyszelenchuk** [comment]
My latest change should fix the issue.
@JanuszHain can you star the project if you use it?

**Comment by JanuszHain** [comment]
@denyszelenchuk I don't use it rn, but sure :)
