### ISSUE TITLE
APK not installing

### ISSUE THREAD

**Issue by AdtrakChrisRutter** [denyszelenchuk/sms-to-slack#2]
I've tried to download and install the app on a Samsung A02s
I've also turned on Install unknown apps.
When I go to APK > then download the app-debug.apk and install, I see the screen #smsToSlack, do you want to install this application?, click install, but it says ' App not installed'.

Anything you can suggest?

**Comment by denyszelenchuk** [comment]
@AdtrakChrisRutter Can you Star this project if you use it?

**Comment by AdtrakChrisRutter** [comment]
@denyszelenchuk I've stared this project. 
However I'm still getting the same problem?
I've redownloaded the app-debug.apk but I'm still getting 'App not installed'
Thanks again for all your help

**Comment by denyszelenchuk** [comment]
Please download latest apk file. It was recently updated.

**Comment by AdtrakChrisRutter** [comment]
Thanks once again, I've downloaded that file (and I can see the difference in file size) however it's still throwing up the same error.

**Comment by denyszelenchuk** [comment]
Have you enabled the apk installation from Unknown sources **Settings → Applications → Unknown sources OR Settings > Security > Unknown Sources**?

**Comment by AdtrakChrisRutter** [comment]
Yeah!
![screenshot_20211103-110533_settings](https://user-images.githubusercontent.com/89591890/140049785-f507aa9a-e915-4e04-9f06-dbadb233bd9f.jpeg)

**Comment by denyszelenchuk** [comment]
OK. Found and fixed the root cause. Try again.

**Comment by AdtrakChrisRutter** [comment]
Amazing! Thank you so much for your help
